### PR TITLE
try win

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR does not work but I'm submitting it anyways in case someone else wants to try this.

@mingwandroid did you ever try to build `rgdal` on Widows? Any advice?

### CODE REVIEW

**Comment by mingwandroid** [comment]
No, I have not tried it yet. Maybe soon.

**Comment by ocefpaf** [comment]
@gillins this is very low priority but if you have some extra time do you mind taking a look at the Windows erros here and see if there is an easy solution?

**Comment by gillins** [comment]
I'm pretty certain you can't mix code created by MSVC (`libgdal`) and code created by gcc (R uses gcc to build, Python uses MSVC to build)... Well some people assert you sometimes can, but I find it never works reliably :frowning_face: 

You will need to have another version of `libgdal` built with gcc for this to work IMHO. Sorry.

**Comment by ocefpaf** [comment]
I'll try that @gillins, thanks!

PS: we do have `r-rnetcdf` and `r-ncdf4` that mix MSVC and gcc. Not sure how battle tested they are though :grimacing:

**Comment by mingwandroid** [comment]
You can mix code generated by the two compilers so long as you pay close attention to some rules.

See rpy2, theano, RStudio and more on defaults for proof that it works.

**Comment by mingwandroid** [comment]
One of the rules is that you cannot mix C++ though, so here we should use the hall gdal recipes from MSYS2.

You could do what libclang does here and make c wrappers to gdal if the do not say exist and call those from the R side C code?

Alternatively we have a few examples in defaults of using MSYS2 recipes directly instead if repacking. If you clone our aggregates super repo and look offer PKGBUILD files then you can see how to do that.  It wasn't difficult, but with a stack as large as gdal it may be more so!

**Comment by gillins** [comment]
> One of the rules is that you cannot mix C++ though

Seems `r-gdal` does indeed use the C++ `gdal` interface rather than the C one so they have made it hard. Not a bad idea to have a `gcc` build of `gdal` on conda-forge though.

**Comment by ocefpaf** [comment]
> It wasn't difficult, but with a stack as large as gdal it may be more so!

Indeed. It will take a lot of time, even from an expert, to get `gdal` going with MSYS gcc.

> Not a bad idea to have a `gcc` build of `gdal` on conda-forge though.

I agree but I don't have the time/experience to try that now. I  may try this at SciPy where I can ask more experienced people for help directly and bribe them with :beer: 

I saw that the default channel has `r-sf`, which depends on `r-rgdal`, but it seems to be a re-package b/c I could not find the recipe for `r-rgdal`.

**Comment by mingwandroid** [comment]
AFAICT `rgdal` (upstream, we don't have packages either) defers to `sf` for all C level linking to `gdal`. Defaults does have `r-sf`, and I use `MSYS2/mingw-w64` packages for `gdal` by the look of it: https://github.com/AnacondaRecipes/r-sf-feedstock/blob/master/recipe/meta.yaml

I don't see win-32 binaries here though: https://anaconda.org/r/r-sf/files .. probably an oversight on my part!

**Comment by ocefpaf** [comment]
> AFAICT `rgdal` (upstream, we don't have packages either) defers to `sf` for all C level linking to `gdal`

I just saw that `r-sf` suggest `r-rgdal` but you can build it with just `gdal` directly.

> and I use `MSYS2/mingw-w64` packages for `gdal` by the look of it

That is awesome! Maybe we can use the same for `r-rgdal`, but I cannot find `m2w64-gdal` or `m2w64-libgdal` when searching `anaconda.org` :-/

**Comment by mingwandroid** [comment]
Hmm, this is odd indeed! I'll check into it when I get back to R.

**Comment by ocefpaf** [comment]
Thanks @mingwandroid! This is low priority for us BTW. Don't worry too much about it.

**Comment by ocefpaf** [comment]
I'm not the right person to get a `gcc` build of `gdal` on Windows. Closing this for now.

**Pull request closed without merging**
